api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
        api_keys: []
    # Active l’interface Swagger UI
    enable_swagger_ui: true
    # Active ReDoc
    enable_re_doc: true
    # Active la doc (openapi.json)
    enable_docs: true
